### PR TITLE
Feat home page

### PR DESCRIPTION
**Pull request by prathmeshjagtap**
Added Home Page and Footer

1)Added Home page
2)Added Footer
3)Added Card Slider
4)Refactored Filter by Category
5)FIxed navbar sticky issues

## To do testing 

Email: test@gmail.com
Password: test@1234

## Files to  Check 
 
Card Slider , Footer
-  [ ] src/frontend/components/cardSlider/CardSlider.jsx
- [ ] src/frontend/components/cardSlider/cardSlider.css
- [ ] src/frontend/components/footer/Footer.jsx
- [ ] src/frontend/pages/home/CategoriesNav.js
- [ ] src/frontend/pages/home/Home.jsx
- [ ] src/frontend/pages/home/SquareCard.jsx
- [ ] src/frontend/pages/home/home.css

## Files you can ignore

Just added products

-[ ] src/backend/db/products.js

Preview Link : https://bookify-bookstore.netlify.app/

### CODE REVIEW

**Review by ishapatell1 — APPROVED** [review]
Prathmesh i like how descriptive your Prs are and small commits make it more understandable!  Further, Your code looks readable and UI clean and smooth. However, you can play around more with colors and card-elements to make it even better. With basic functionalities, Amazing App.

**Review by SukanyaSen530 — APPROVED** [review]
Wish could see the UI.

**Comment by prathmeshjagtap** [comment]
> Wish could see the UI.

I have added it

**Comment by prathmeshjagtap** [comment]
> Wish could see the UI.

I though you could see through netlify preview , but it was not deployed

**Comment by prathmeshjagtap** [comment]
> > Wish could see the UI.
> 
> I thought you could see through netlify preview, but it was not deployed

here is the Preview Link : https://bookify-bookstore.netlify.app/

**Pull request merged**
