### PR TITLE
feat-added products Page

### PR DESCRIPTION
**Pull request by prathmeshjagtap**
1)Added Navbar Components
2)Added E-commerce  Card Components
     a)Product card
     b)Wishlist card 
3)Added Filter  Component Which Includes all the Filters

4)Added Everything in Products Page to Display
5)Used UseEffect for now in Products Page to get data from the API and Display. To check if Everything is Working

6)Added default styles in the index.css and Respective Component Styles in respective Folders. 

## What not to check 

Responsiveness of the Page

### CODE REVIEW

**Review by ishapatell1 — APPROVED** [review]
The live preview link is not working prathmesh..please see to it. 
Else, your code is clean  and understandable.

**Review by Kavita539 — COMMENTED** [review]
- Could not preview the live project, it says "Page Not Found". If you could look into it.
- Nicely written code, loved the approach of breaking the code into pieces.
- Well maintained.

**Comment by prathmeshjagtap** [comment]
> * Could not preview the live project, it says "Page Not Found". If you could look into it.
> * Nicely written code, loved the approach of breaking the code into pieces.
> * Well maintained.

hey I changes the  live preview link its working now just click on Products from home Page

**Comment by prathmeshjagtap** [comment]
> The live preview link is not working prathmesh..please see to it. Else, your code is clean and understandable.

yes I changed the link its working now

**Review by Kavita539 — APPROVED** [review]

**Comment by Kavita539** [comment]
> > * Could not preview the live project, it says "Page Not Found". If you could look into it.
> > * Nicely written code, loved the approach of breaking the code into pieces.
> > * Well maintained.
> 
> hey I changes the live preview link its working now just click on Products from home Page

Yeah approved the changes!

**Pull request merged**
